name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 安装 依赖
      run: sudo apt update && sudo apt upgrade -y && sudo apt install -y ccache libdebuginfod1
      
    - name: configure
      run: chmod +x build.sh && ./build.sh

    - name: Upload all ZIP files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zip-files
        path: |
          **/*.zip
        if-no-files-found: warn
